### ISSUE TITLE
Unrecognized field ownerName

### ISSUE THREAD

**Issue by ju5tler** [maximilianvoss/spotify-toniebox-sync#14]
Hi,

after setting up everything I run the script (just to sync it once, not the daemon) and get this error in spotify-toniebox-sync.log:

28 May 2020 17:40:34,354 - ERROR:rocks.voss.spotifytonieboxsync.Application:main:71: IOException
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: **Unrecognized field "ownerName"** (class rocks.voss.toniebox.beans.toniebox.Household), not marked as ignorable (6 known properties: , "access", "canLeave", "id", "image", "name", "foreignCreativeTonieContent"])
 at [Source: N/A; line: -1, column: -1] (through reference chain: rocks.voss.toniebox.beans.toniebox.Household["ownerName"])
        at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:79)
        at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:555)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:708)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1160)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:315)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)
        at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:151)
        at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:18)
        at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:2860)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1569)
        at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:1902)
        at rocks.voss.toniebox.beans.Transformer.createBean(Transformer.java:23)
        at rocks.voss.toniebox.beans.Transformer.createBean(Transformer.java:16)
        at rocks.voss.toniebox.RequestHandler.executeRequest(RequestHandler.java:149)
        at rocks.voss.toniebox.RequestHandler.executeGetRequest(RequestHandler.java:106)
        at rocks.voss.toniebox.RequestHandler.getHouseholds(RequestHandler.java:55)
        at rocks.voss.toniebox.TonieHandler.getHouseholds(TonieHandler.java:55)
        at rocks.voss.spotifytonieboxsync.Application.main(Application.java:62)

Toniebox User (Email) and Password are correct. Checked 3 times...and copied & pasted from the same source(keypass) that I use to login to the Tonies side.

Any idea?

Thanks a lot.

**Comment by mrad86** [comment]
Hello,
this issue was fixed already.  See closed Issue #2 IOException in tonieHandler - Issue: "Unrecognized field "ownerName

**Comment by ju5tler** [comment]
Hi,

sorry, my fault. I was only looking at the open issues, not the closed ones. Missed the fix.

I edited pom.xml to use 2.6 of the toniebox-api. 

Now I have another issue, with householdId, which is also fixed already, but not merged. 
https://github.com/maximilianvoss/toniebox-api/pull/4

But I will close this, as it is a different issue as the one I initially reported.

Thanks for the hint.
