### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by n3roGit** [maximilianvoss/spotify-toniebox-sync#15]
I got the following error:

/tonie/spotify-toniebox-sync/target# java -jar spotify-toniebox-sync-1.3-SNAPSHOT-jar-with-dependencies.jar --apicode
Jun 05, 2020 7:02:30 PM com.wrapper.spotify.SpotifyHttpManager makeUri
SEVERE: URI Syntax Exception for "<redirectUri>"
Exception in thread "main" java.lang.NullPointerException
        at com.wrapper.spotify.requests.authorization.authorization_code.AuthorizationCodeUriRequest$Builder.redirect_uri(AuthorizationCodeUriRequest.java:74)
        at com.wrapper.spotify.SpotifyApi.authorizationCodeUri(SpotifyApi.java:406)
        at rocks.voss.spotifytonieboxsync.SpotifyAuthenticationSetup.getSignInUrl(SpotifyAuthenticationSetup.java:29)
        at rocks.voss.spotifytonieboxsync.Application.main(Application.java:40)

**Comment by HHEN** [comment]
Same here

**Comment by bergerf** [comment]
edit /main/resources/spotify-toniebox-sync.properties with your spotify clientid and secret, rebuild and run again...
