### ISSUE TITLE
Keep getting transcodingErrors when it's trying to upload to Tonie

### ISSUE THREAD

**Issue by Grisgruis** [maximilianvoss/spotify-toniebox-sync#28]
Ola, 

Got a question got the project up and running but keep getting the following error

```
23 Jan 2021 12:52:20,448 - INFO:rocks.voss.musicsync.plugins.output.toniebox.TonieboxOutputPlugin:getCreativeTonie:201: IOException
com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_OBJECT token
 at [Source: N/A; line: -1, column: -1] (through reference chain: rocks.voss.toniebox.beans.toniebox.CreativeTonie["transcodingErrors"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:164)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:575)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseString(StdDeserializer.java:612)
	at com.fasterxml.jackson.databind.deser.std.StringArrayDeserializer.deserialize(StringArrayDeserializer.java:69)
	at com.fasterxml.jackson.databind.deser.std.StringArrayDeserializer.deserialize(StringArrayDeserializer.java:18)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:464)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:98)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:295)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:18)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:2860)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1569)
	at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:1902)
	at rocks.voss.toniebox.beans.Transformer.createBean(Transformer.java:26)
	at rocks.voss.toniebox.beans.Transformer.createBean(Transformer.java:17)
	at rocks.voss.toniebox.RequestHandler.executeRequest(RequestHandler.java:181)
	at rocks.voss.toniebox.RequestHandler.executeGetRequest(RequestHandler.java:133)
	at rocks.voss.toniebox.RequestHandler.getCreativeTonies(RequestHandler.java:82)
	at rocks.voss.toniebox.TonieHandler.getCreativeTonies(TonieHandler.java:64)
	at rocks.voss.musicsync.plugins.output.toniebox.TonieboxOutputPlugin.getCreativeTonie(TonieboxOutputPlugin.java:189)
	at rocks.voss.musicsync.plugins.output.toniebox.TonieboxOutputPlugin.orderTracks(TonieboxOutputPlugin.java:70)
	at rocks.voss.musicsync.Application.sync(Application.java:75)
	at rocks.voss.musicsync.Application.main(Application.java:52)

```

full log [https://pastebin.com/1k00r3vP](https://pastebin.com/1k00r3vP)

Platform:
```
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-0ubuntu1~20.10-b01)
OpenJDK 64-Bit Server VM (build 25.275-b01, mixed mode)
```

It actually authenticates because when I change my credentials I get different kind of errors, also checked the creative tonie id like a 100 times :(

Any idea where to look?

Chris,

**Comment by maximilianvoss** [comment]
is fixed with latest version
