### ISSUE TITLE
File doesn't exists

### ISSUE THREAD

**Issue by schniedan** [maximilianvoss/spotify-toniebox-sync#29]
Hi! Thanks heaps for this project! I think I'll make great use of it once I get it to work :)

I'm getting the error below when trying to sync - any ideas? It seems to be reading the playlist just fine but then failing on the individual songs.

07 Feb 2021 14:15:07,242 - INFO:rocks.voss.musicsync.plugins.input.spotify.SpotifyRecordingHandler:isFileValid:95: File doesn't exists
07 Feb 2021 14:15:07,244 - INFO:rocks.voss.musicsync.plugins.input.spotify.SpotifyRecordingHandler:downloadFile:37: Downloading: spotify:track:1eMhNaN4a92qoidBbkQCmG
07 Feb 2021 14:15:07,875 - ERROR:rocks.voss.musicsync.plugins.output.toniebox.TonieboxOutputPlugin:uploadTracks:48: IOException
java.io.FileNotFoundException: /Users/andreasprivate/dev/tools/spotify-toniebox-sync/package/target/output/cache/1eMhNaN4a92qoidBbkQCmG.mp3 (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.apache.http.entity.mime.content.FileBody.writeTo(FileBody.java:116)
	at org.apache.http.entity.mime.AbstractMultipartForm.doWriteTo(AbstractMultipartForm.java:134)
	at org.apache.http.entity.mime.AbstractMultipartForm.writeTo(AbstractMultipartForm.java:157)
	at org.apache.http.entity.mime.MultipartFormEntity.writeTo(MultipartFormEntity.java:113)
	at org.apache.http.impl.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:156)
	at org.apache.http.impl.conn.CPoolProxy.sendRequestEntity(CPoolProxy.java:160)
	at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:238)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at rocks.voss.toniebox.RequestHandler.executeRequest(RequestHandler.java:176)
	at rocks.voss.toniebox.RequestHandler.executePostRequest(RequestHandler.java:147)
	at rocks.voss.toniebox.RequestHandler.uploadFile(RequestHandler.java:115)
	at rocks.voss.toniebox.beans.toniebox.CreativeTonie.uploadFile(CreativeTonie.java:76)
	at rocks.voss.musicsync.plugins.output.toniebox.TonieboxOutputPlugin.uploadTracks(TonieboxOutputPlugin.java:44)
	at rocks.voss.musicsync.Application.sync(Application.java:74)
	at rocks.voss.musicsync.Application.main(Application.java:52)

Has some notation in the spotify universe changed? Does it need additional permissions to download the file?

Java-Version
java -version 
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.252-b09, mixed mode)

On MacOS Big Sur 11.1

Would be great if you could help!

Thanks,
Andreas

P.S.: It should be "File doesn't exist" :)
Also, I needed to apply the parseArgs fix that's described in the issues section already - maybe pull that into the code? https://github.com/maximilianvoss/spotify-toniebox-sync/issues/23

**Comment by schniedan** [comment]
A figured out a few more bits to the error:
The downloadFile method swallows cmd line errors when it tries to execute the "./stream_recorder.pl --uri ..." cmd.

So on my MacOS machine it's missing ffmpeg in a first step. When I managed to get that installed via homebrew, I'm now in "dependency and permission denied wonderland" for  

Missing Binaries: 
  - sox (worked)
  - spotify (keeps throwing errors via homebrew)
  - sp (not on homebrew)
  - pacmd (not on homebrew)
  - pactl (not on homebrew)
  - qdbus (not on homebrew)

Tired for tonight. Might continue another day :(

**Comment by schniedan** [comment]
Ok, I cobbled myself through some homebrew equivalents of the libs above and manually linking some of them to /usr/local/bin but it's still far from working. Next issue is that homebrew pidof doesn't have an "-- s" option...

I might keep trying but I guess the short answer is: Don't try to run this on MacOS, and don't even think about Windows... :)

Once I get it to work on a linux thingy, I'll send a big thank you!

**Comment by schniedan** [comment]
So, I'll close this thread. My conclusion: Homebrew on current macOS Bug Sur 11.2 is not happy with this :) I'll continue on a different thread where current Ubuntu inside a VM works much better :) Thanks anyway Max!
