### ISSUE TITLE
IOException during sync execution:  java.io.FileNotFoundException: /tmp/spotify-toniebox-sync/3ZyLXDbAoQucsyaRQlxYql.mp3 (Datei oder Verzeichnis nicht gefunden)

### ISSUE THREAD

**Issue by erikp152** [maximilianvoss/spotify-toniebox-sync#3]
@maximilianvoss Sry, but I am having the same issue, building and using a new *.jar after your merge. The error-message is the same as i wrote in https://github.com/maximilianvoss/spotify-toniebox-sync/issues/2#issue-543227279.

@maximilianvoss + @JonasBrand Had you tested the fix? Am i wrong or isn't this fix working at all?

**Comment by JonasBrand** [comment]
Hi @erikp152,

the fix was so far only applied in the `toniebox-api` repository and `spotify-toniebox-sync` was not yet updated with the new version of the library. You can change the version in the [pom.xml](https://github.com/maximilianvoss/spotify-toniebox-sync/blob/master/pom.xml#L44) to 2.6 in order to use the new version.

@maximilianvoss Are you planning to release a new version of `spotify-toniebox-sync` to use the new library version?

Regards
Jonas

**Comment by erikp152** [comment]
@JonasBrand I got it. I changed the pom.xml in spotify-toniebox-sync as well to version 2.6 - it is working now after building a new *.jar with all dependencies. 

Now i have the following problem:
````
13 März 2020 22:07:44,415 - INFO:rocks.voss.spotifytonieboxsync.SpotifyRecordingHandler:recordTrack:21: Downloading: spotify:track:3ZyLXDbAoQucsyaRQlxYql
13 März 2020 22:07:45,923 - ERROR:rocks.voss.spotifytonieboxsync.Application:daemonExecution:112: IOException during sync execution: 
java.io.FileNotFoundException: /tmp/spotify-toniebox-sync/3ZyLXDbAoQucsyaRQlxYql.mp3 (Datei oder Verzeichnis nicht gefunden)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at org.apache.http.entity.mime.content.FileBody.writeTo(FileBody.java:116)
	at org.apache.http.entity.mime.AbstractMultipartForm.doWriteTo(AbstractMultipartForm.java:134)
	at org.apache.http.entity.mime.AbstractMultipartForm.writeTo(AbstractMultipartForm.java:157)
	at org.apache.http.entity.mime.MultipartFormEntity.writeTo(MultipartFormEntity.java:113)
	at org.apache.http.impl.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:156)
	at org.apache.http.impl.conn.CPoolProxy.sendRequestEntity(CPoolProxy.java:152)
	at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:238)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at rocks.voss.toniebox.RequestHandler.executeRequest(RequestHandler.java:154)
	at rocks.voss.toniebox.RequestHandler.executePostRequest(RequestHandler.java:125)
	at rocks.voss.toniebox.RequestHandler.uploadFile(RequestHandler.java:93)
	at rocks.voss.toniebox.beans.toniebox.CreativeTonie.uploadFile(CreativeTonie.java:75)
	at rocks.voss.spotifytonieboxsync.Application.transferFromSpotifyToToniebox(Application.java:226)
	at rocks.voss.spotifytonieboxsync.Application.sync(Application.java:165)
	at rocks.voss.spotifytonieboxsync.Application.daemonExecution(Application.java:106)
	at rocks.voss.spotifytonieboxsync.Application.main(Application.java:66)
````

The directory is granted with access for everyone - do you have an idea? Thanks a lot!

**Comment by erikp152** [comment]
@JonasBrand + @maximilianvoss After adding this file manually without content and reducing the playlist to only one track, I receive the following error:
````
13 März 2020 22:41:48,172 - ERROR:rocks.voss.spotifytonieboxsync.Application:main:71: IOException
com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_OBJECT token
 at [Source: N/A; line: -1, column: -1] (through reference chain: rocks.voss.toniebox.beans.toniebox.CreativeTonie["transcodingErrors"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:164)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:575)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseString(StdDeserializer.java:612)
	at com.fasterxml.jackson.databind.deser.std.StringArrayDeserializer.deserialize(StringArrayDeserializer.java:69)
	at com.fasterxml.jackson.databind.deser.std.StringArrayDeserializer.deserialize(StringArrayDeserializer.java:18)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:464)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:98)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:295)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:18)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:2860)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1569)
	at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:1902)
	at rocks.voss.toniebox.beans.Transformer.createBean(Transformer.java:23)
	at rocks.voss.toniebox.beans.Transformer.createBean(Transformer.java:16)
	at rocks.voss.toniebox.RequestHandler.executeRequest(RequestHandler.java:159)
	at rocks.voss.toniebox.RequestHandler.executeGetRequest(RequestHandler.java:111)
	at rocks.voss.toniebox.RequestHandler.getCreativeTonies(RequestHandler.java:60)
	at rocks.voss.toniebox.TonieHandler.getCreativeTonies(TonieHandler.java:64)
	at rocks.voss.spotifytonieboxsync.Application.main(Application.java:63)
````

Do you have an idea?

**Comment by udovic2100** [comment]
I have the same issue. Any ideas?

**Comment by DaChunky** [comment]
Hi, I had the same issue. The problem is that in the "SpotifyRecordingHandler.java" file the case that the execution of "stream_recorder.pl" return an error is not handled. 
`Process proc = rt.exec(commands);`
`proc.waitFor();`
` log.debug("Execution done");`
That the process came back does not mean it was successful. It only means that the process finished. Afterwards it has to be checked that the requested file was created. It could be done by:
`File fileInfo = new File(spotifyHandler.getCachePath(), filename);`
`if (not fileInfo.exists) {`
`  throws new IOException("stream_recorder.pl failed to create file: " + fileInfo.getPath())`
`}`
To find out why "stream_recorder.pl" fails, enlarge log level in the log4j properties file to debug and search for the line:
`... Executing: stream_recorder.pl --uri ...`
And run this command from terminal. In my case some packages were missing like "sp". "sp" you can find within the repo under "bin". But to use it you have to make it executable via
`chmod u+x sp`
and create a link, as described on the README, to make it available via "/usr/bin/" or "/usr/local/bin".

**Comment by erikp152** [comment]
@maximilianvoss seems like it is a general problem? do you give some assistance to that error, pls? Thank you.

**Comment by DaChunky** [comment]
@erikp152: I already ask the owner of this repo if I could upload my fix to this repo. The Readme has to be reviewed as well. Unfortunately he did not answer. But is no big deal to do it on your on. I described the important steps in my last comment.

**Comment by erikp152** [comment]
@DaChunky Can you push your changes in a merge-request, so that the owner can easily include it? I will go through your description as well, thanks.

**Comment by maximilianvoss** [comment]
Hi, 
sorry for the late reply. I started doing a full refactoring of the code a couple month ago. Please try the code in the v2.0 branch.
