### ISSUE TITLE
SpotifyWebApiException: Invalid client

### ISSUE THREAD

**Issue by Keynaan** [maximilianvoss/spotify-toniebox-sync#31]
Heyho,

thank you for your awesome work.

The installation of `spotify-toniebox-sync`, generation of spotify URI and access token went like a blast but unfortunately, I get the following error running the daemon as well as single cmd:
```
$ ./musicsync --input spotify:playlist:XXXfoobarXXX --output toniebox:XXX-XXX-XXX-XXX-XXXfoobar:XXXfoobar

02 Jul 2021 21:15:53,702 - ERROR:rocks.voss.musicsync.plugins.input.spotify.SpotifyInputPlugin:establishConnection:28: SpotifyWebApiException
com.wrapper.spotify.exceptions.detailed.BadRequestException: Invalid client
	at com.wrapper.spotify.SpotifyHttpManager.getResponseBody(SpotifyHttpManager.java:298)
	at com.wrapper.spotify.SpotifyHttpManager.post(SpotifyHttpManager.java:174)
	at com.wrapper.spotify.requests.AbstractRequest.postJson(AbstractRequest.java:131)
	at com.wrapper.spotify.requests.authorization.authorization_code.AuthorizationCodeRefreshRequest.execute(AuthorizationCodeRefreshRequest.java:33)
	at rocks.voss.musicsync.plugins.input.spotify.SpotifyAuthenticationSetup.refreshToken(SpotifyAuthenticationSetup.java:43)
	at rocks.voss.musicsync.plugins.input.spotify.SpotifyInputPlugin.establishConnection(SpotifyInputPlugin.java:24)
	at rocks.voss.musicsync.Application.sync(Application.java:61)
	at rocks.voss.musicsync.Application.main(Application.java:42)
02 Jul 2021 21:15:54,962 - ERROR:rocks.voss.musicsync.plugins.input.spotify.SpotifyInputPlugin:getTracklist:88: SpotifyWebApiException
com.wrapper.spotify.exceptions.detailed.UnauthorizedException: Invalid access token
	at com.wrapper.spotify.SpotifyHttpManager.getResponseBody(SpotifyHttpManager.java:300)
	at com.wrapper.spotify.SpotifyHttpManager.get(SpotifyHttpManager.java:154)
	at com.wrapper.spotify.requests.AbstractRequest.getJson(AbstractRequest.java:117)
	at com.wrapper.spotify.requests.data.playlists.GetListOfCurrentUsersPlaylistsRequest.execute(GetListOfCurrentUsersPlaylistsRequest.java:35)
	at rocks.voss.musicsync.plugins.input.spotify.PlaylistHandler.getPlaylists(PlaylistHandler.java:29)
	at rocks.voss.musicsync.plugins.input.spotify.SpotifyInputPlugin.getTracklist(SpotifyInputPlugin.java:72)
	at rocks.voss.musicsync.Application.sync(Application.java:64)
	at rocks.voss.musicsync.Application.main(Application.java:42)
```

spotify is installed, logged in, running and checked via VNC.

Versions:
spotify-toniebox-sync: latest master
spotify: 1.1.55.498.gf9a83c60
OS: Ubuntu 18.04.5 LTS

Do you have any thoughts on this. I checked the access token like a hundred times, so I think the problem is the earlier error regarding the `Invalid client`.

Best regards

**Comment by maximilianvoss** [comment]
fixed with the latest version
