### ISSUE TITLE
IO Eception during sync: IOException com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException

### ISSUE THREAD

**Issue by andyman3000** [maximilianvoss/spotify-toniebox-sync#8]
Hi, first of all, thanks for the great work! Unfortunately I cannot get this to work. It seems there is a problem with the Household returned from the tonies site. Do you have ay idea what might be the reason? Unfortunately my JAVA knowledge is very limited.

Here ist the stacktrace:

ERROR:rocks.voss.spotifytonieboxsync.Application:main:71: IOException
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "ownerName" (class rocks.voss.toniebox.beans.toniebox.Household), not marked as ignorable (6 known properties: , "access", "canLeave", "id", "image", "name", "foreignCreativeTonieContent"])
 at [Source: N/A; line: -1, column: -1] (through reference chain: rocks.voss.toniebox.beans.toniebox.Household["ownerName"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:79)
	at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:555)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:708)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1160)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:315)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:18)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:2860)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1569)
	at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:1902)
	at rocks.voss.toniebox.beans.Transformer.createBean(Transformer.java:23)
	at rocks.voss.toniebox.beans.Transformer.createBean(Transformer.java:16)
	at rocks.voss.toniebox.RequestHandler.executeRequest(RequestHandler.java:149)
	at rocks.voss.toniebox.RequestHandler.executeGetRequest(RequestHandler.java:106)
	at rocks.voss.toniebox.RequestHandler.getHouseholds(RequestHandler.java:55)
	at rocks.voss.toniebox.TonieHandler.getHouseholds(TonieHandler.java:55)
	at rocks.voss.spotifytonieboxsync.Application.main(Application.java:62)

**Comment by udovic2100** [comment]
Have a look at issue #2 . This has been solved already.
